### ISSUE TITLE
Does this code still work of have GoDaddy blocked it?

### ISSUE THREAD

**Issue by kelvtech-co-uk** [x86driver/godaddy-ddns#1]
Hi, thanks for putting your code/solution on Github.  I've been trying all day to get pygodaddy working but it always fails when updating the dns record.   My coding skills aren't the best but I was hoping you'd be able to confirm whether this code should still work or whether GoDaddy have changed things at their side which has stopped it working?

**Comment by x86driver** [comment]
Hi Kelvin:
This code can work, and I tested it just now. I use pygodaddy 0.1.6

Could you check your username/password in godaddy.py? It's the username/password that can login to godaddy website. Also, could you paste your command and error message?

**Comment by kelvtech-co-uk** [comment]
Hey, thank you for getting back to me.  I am using pygodaddy 0.1.6 and have all the dependencies installed, I've tested the code line by line and all seems fine i.e. I can successfully login, I've manually tested with a 'client.is_loggedin()' which returns TRUE.  The error (as below) is when it try's to update the dns record with my new IP...I've tried a couple of different pygodaddy solutions now and they fail for me at the same point.  

Do I need an initial GoDaddy DNS setup for this to work?  I only have 1 domain with GoDaddy at the moment and don't plan to increase this anytime soon so my DNS 'A' record I have manually set as 'Host = @' but I've tried replacing this with the actual domain name and this fails at the same point too.

My shell output:-
python doremi.py @
@
Get IP...(x.x.x.x) <--I removed my real IP from here.
Logging into GoDaddy...
Updating IP...
Update fail!

Thanks for the help.

**Comment by x86driver** [comment]
OK, if you have the domain example.com, and you want to update ftp.example.com, you can try to do:

$ python godaddy.py ftp.example.com

This code use complete domain name, eg., example.com or ftp.example.com, neither @ nor ftp.

And this code have a bug, if you want to update a hostname with the same IP, it will show update fail (because I didn't check this situation).

**Comment by kelvtech-co-uk** [comment]
I'm not using sub domains neither do I have a need (as far as I understand) to use an actual hostname...I just want my entire domain pointed at my IP...therefore I think the correct syntax for me should be..

$ python godaddy.py example.com

So the 'A' record that GoDaddy will hold will/should have 'Host = example.com'.  Have I got this all right?

**Comment by x86driver** [comment]
Yes, correct. You can login to godaddy website to check that.

**Comment by kelvtech-co-uk** [comment]
Still the same result...update failed! :-(

**Comment by x86driver** [comment]
Could you try this:

$ python godaddy.py yourdomain.com 192.168.100.100

If success, then:

$ python godaddy.py yourdomain.com

This code has a bug, if you have already a DNS A record, and you update with the same IP, it will show update fail (because it's not need to update).

**Comment by kelvtech-co-uk** [comment]
Again, failed at the first line...$ python godaddy.py yourdomain.com 192.168.100.100

**Comment by x86driver** [comment]
Hi, is it possible to modify DNS A record of yourdomain.com on godaddy website manually?

**Comment by kelvtech-co-uk** [comment]
Hey, yes I can...without issue.  My DNS record on GoDaddy has only a A record configured I purposefully configured it with an incorrect IP so I could see a successful update using your code.

I noticed on the DNS configuration page they offer a link to what they call a "Classic DNS Tool" which has a different UI but does effectively the same job as in it facilities the management of the DNS record.  Could this be interfering?

**Comment by x86driver** [comment]
Hi, I've found some problems. I use another godaddy account, and try to update some domain, sometimes I got an exception:

```
Traceback (most recent call last):
  File "godaddy.py", line 29, in <module>
    if client.login(username, password):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygodaddy/client.py", line 96, in login
    r = self.session.get(self.default_url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dns.godaddy.com', port=443): Max retries exceeded with url: /default.aspx (Caused by <class 'socket.error'>: [Errno 54] Connection reset by peer)
```

But sometimes it works well. I think pygodaddy simulates browser's action about login, update. I haven't trace it for sure. Maybe we can add some debug code on pygodaddy?

**Comment by kelvtech-co-uk** [comment]
Yes, I agree...i think pygodaddy is simulating browser actions as well.  I added the following line into your code just before the client.login line... ('import logging' needed up top)

logging.basicConfig(filename="/home/kelvin/godaddy/doremi.log", format='%(asctime)s %(message)s', level=logging.DEBUG)

The output is below, if I'm reading it correctly then the HTTP status codes near the end of line all look okay...

$ cat doremi.log 
2015-01-05 15:47:49,103 Starting new HTTPS connection (1): dns.godaddy.com
2015-01-05 15:47:49,837 Setting read timeout to None
2015-01-05 15:47:50,019 "GET /default.aspx HTTP/1.1" 302 202
2015-01-05 15:47:50,021 Starting new HTTPS connection (1): idp.godaddy.com
2015-01-05 15:47:50,753 Setting read timeout to None
2015-01-05 15:47:51,261 "GET /login.aspx?SPKey=GDDNS-M1-004&myaUrl=%2fdefault.aspx& HTTP/1.1" 200 17871
2015-01-05 15:47:51,435 Setting read timeout to None
2015-01-05 15:47:52,973 "POST /login.aspx?SPKey=GDDNS-M1-004&myaUrl=%2fdefault.aspx& HTTP/1.1" 302 227
2015-01-05 15:47:52,981 Setting read timeout to None
2015-01-05 15:47:53,195 "GET /login_redirect.aspx?artifact=euCiaXJxmHJxIAANDgRdgtxocdSvhkCm&myaUrl=/default.aspx HTTP/1.1" 302 132
2015-01-05 15:47:53,199 Setting read timeout to None
2015-01-05 15:47:54,401 "GET /default.aspx HTTP/1.1" 200 28815
2015-01-05 15:47:54,577 Setting read timeout to None
2015-01-05 15:47:55,496 "GET /ZoneFile.aspx?zoneType=0&sa=&zone=co.uk HTTP/1.1" 200 42135
2015-01-05 15:47:55,671 Setting read timeout to None
2015-01-05 15:47:55,848 "POST /ZoneFile_WS.asmx/AddNewARecord HTTP/1.1" 200 117

#confused :-(

**Comment by x86driver** [comment]
Hi:
Did you mask the above log for zone=co.uk

```
2015-01-05 15:47:55,496 "GET /ZoneFile.aspx?zoneType=0&sa=&zone=co.uk HTTP/1.1" 200 42135
```

My log like this:

```
2015-01-05 15:47:55,496 "GET /ZoneFile.aspx?zoneType=0&sa=&zone=myhost.com HTTP/1.1" 200 42135
```

Could you help me to check that? Thanks!

**Comment by kelvtech-co-uk** [comment]
Hey, no I didn't edit the log to remove details my line...
'''
2015-01-05 15:47:55,496 "GET /ZoneFile.aspx?zoneType=0&sa=&zone=co.uk HTTP/1.1" 200 42135
'''
...is a raw copy/paste!?

**Comment by x86driver** [comment]
OK, if it's raw copy, I found the difference is

```
zone=co.uk
```

My log shows like

```
zone=myhost.co.uk
```

not

```
zone=co.uk
```

Maybe a problem?

**Comment by sbtristan98** [comment]
Ok i have discovered several problems with pygodaddy in the recent days. First i found thet Public_Get_Ip is a third party service which went down about 5 days ago. So i changed my code to "public_ip = urllib2.urlopen("http://myip.dnsdynamic.org/").read()" with urllib2 as an import for python.

Now i have an even bigger problem is that PyGodaddy isn't replacing the DNS record like it use to.
I can't Program python at all and i have no idea what to do except going manual until there is a solution.

Tristan

**Comment by x86driver** [comment]
Hello ultraman245:

Do you mean you can't update DNS record like:

```
$ python godaddy.py yourdomain.com 1.2.3.4
```

**Comment by sbtristan98** [comment]
No i mean it replies to me that the dns has been updated with my correct external ip, yet It doesn't update in my godaddy dns zone file. Wierd i never touched the code and it was working for months.

My DDNS scrypt is:
#!/usr/bin/env python 
import logging
import urllib2
import pygodaddy

logging.basicConfig(filename='godaddy.log', format='%(asctime)s %(message)s', level=logging.INFO)
GODADDY_USERNAME="(My Username)"
GODADDY_PASSWORD="(My Password)"
client = pygodaddy.GoDaddyClient()
client.login(GODADDY_USERNAME, GODADDY_PASSWORD)

for domain in client.find_domains():
    dns_records = client.find_dns_records(domain)

public_ip = urllib2.urlopen("http://myip.dnsdynamic.org/").read()
domain = "(My domain 1)"
logging.debug("Domain '{0}' DNS records: {1}".format(domain, dns_records))
if public_ip != dns_records[0].value:
 client.update_dns_record(domain, public_ip)
 logging.info("Domain '{0}' public IP set to '{1}'".format(domain, public_ip))

for test in client.find_domains():
    dns_records = client.find_dns_records(test)

test = "(my domain 2)"
logging.debug("Domain '{0}' DNS records: {1}".format(test, dns_records))
print client.find_domains()
if public_ip != dns_records[0].value:
 client.update_dns_record(test, public_ip)
 logging.info("Domain '{0}' public IP set to '{1}'".format(test, public_ip))

client.update_dns_record(test, public_ip)

if public_ip == dns_records[0].value:
 print(public_ip)
 print(dns_records[0].value)

**Comment by x86driver** [comment]
I found I can't update DNS record these days, like @KillerKelvUK

**Comment by x86driver** [comment]
Hi all:

After I upgrade pygodaddy to 0.1.7, it works!

**Comment by x86driver** [comment]
Hi all:

pygodaddy has 0.2.0,
we can try it.

I'm using 0.1.7, and it can work.

**Comment by x86driver** [comment]
Finally, I switch to gandi.net
They have native API.

See: https://github.com/doremi/gandi-ddns
