### ISSUE TITLE
Update fails everytime

### ISSUE THREAD

**Issue by archerne** [x86driver/godaddy-ddns#2]
This script used to work, but I have updated to pygodaddy ver 1.0.8 and it hasn't worked since. I did notice that godaddy did an update to their DNS Manager recently. Any ideas on why it is failing to update now?

**Comment by x86driver** [comment]
Hi @archerne,
I found pygodaddy has ver 0.2.0, maybe you can try it.
I'm using 0.1.7, it seems work.

``` shell```
doremi@mac:~ $ pip-2.7  search pygodaddy
pygodaddy                 - 3rd Party Client Library for Manipulating Go Daddy DNS Records.
  INSTALLED: 0.1.7
  LATEST:    0.2.0
```

**Comment by x86driver** [comment]
Hi @archerne 

I don't use godaddy anymore, instead, I switch to gandi.net
They have native API.

See: https://github.com/doremi/gandi-ddns
